CREATE OR REPLACE FORCE VIEW VW_MATCH_HISTORY AS
SELECT PL1.NICKNAME PLAYER,
       PL2.NICKNAME OPPONENT,
       MH.DATE_GAME,
       MH.VICTORY
  FROM MATCH_HISTORY MH,
       PLAYER PL1,
       PLAYER PL2
 WHERE MH.IDPLAYER = PL1.ID
   AND MH.IDPLAYER_OPPO = PL2.ID
