CREATE OR REPLACE FORCE VIEW VW_PLAYER_BY_LEVEL AS
SELECT SC.DESCRICAO,
       COUNT(PL.ID) PLAYERS
  FROM SCORE SC,
       PLAYER PL
 WHERE PL.SCORE >= SC.PONTUACAO_INI
   AND PL.SCORE <= SC.PONTUACAO_FIM
GROUP BY SC.DESCRICAO
