DROP INDEX IND_GAME_BOARD_IDROOM;
DROP INDEX IND_GAME_BOARD_IDPLAYER;
DROP TABLE GAME_BOARD;
DROP INDEX IND_ROOM_PLAYER_DATE_JOIN;
DROP INDEX IND_ROOM_IDROOM;
DROP INDEX IND_ROOM_IDPLAYER;
DROP TABLE ROOM_PLAYER;
DROP SEQUENCE ROOM_ID;
DROP TABLE ROOM;
DROP TABLE MATCH_HISTORY;
DROP INDEX IND_PLAYER_NICKNAME_PAS;
DROP SEQUENCE PLAYER_ID;
DROP TABLE PLAYER;
DROP SEQUENCE ICON_ID;
DROP TABLE ICON;
DROP SEQUENCE SCORE_ID;
DROP TABLE SCORE;

CREATE TABLE ICON(
  ID NUMBER(10) NOT NULL,
  NAME VARCHAR(30) NOT NULL,
  ADDRESS VARCHAR(150) NOT NULL,
  CONSTRAINT PK_ICON PRIMARY KEY (ID),
  CONSTRAINT UK_ICON_NAME UNIQUE (NAME),
  CONSTRAINT UK_ICON_ADDRESS UNIQUE (ADDRESS)
);
CREATE SEQUENCE ICON_ID;

CREATE TABLE PLAYER(
  ID NUMBER(10) NOT NULL,
  NICKNAME VARCHAR2(16) NOT NULL,
  PASSWORD VARCHAR2(100) NOT NULL,
  SCORE NUMBER(10) NOT NULL,
  ACTIVE NUMBER(1) DEFAULT 0 NOT NULL,
  ICON_GAME NUMBER(10) NOT NULL,
  CONSTRAINT PK_PLAYER PRIMARY KEY (ID),
  CONSTRAINT FK_PLAYER_ICON_GAME FOREIGN KEY (ICON_GAME) REFERENCES ICON(ID)
);
CREATE SEQUENCE PLAYER_ID;
CREATE UNIQUE INDEX IND_PLAYER_NICKNAME_PAS ON PLAYER(NICKNAME, PASSWORD);

CREATE TABLE ROOM(
  ID NUMBER(10) NOT NULL,
  NAME VARCHAR2(20) NOT NULL,
  CONSTRAINT PK_ROOM PRIMARY KEY (ID),
  CONSTRAINT UK_ROOM_NAME UNIQUE (NAME)
);
CREATE SEQUENCE ROOM_ID;

CREATE TABLE ROOM_PLAYER(
  IDROOM NUMBER(10) NOT NULL,
  IDPLAYER NUMBER(10) NOT NULL,
  DATE_JOIN DATE NOT NULL,
  CONSTRAINT PK_ROOM_PLAYER PRIMARY KEY (IDROOM, IDPLAYER),
  CONSTRAINT FK_ROOM FOREIGN KEY (IDROOM) REFERENCES ROOM(ID),
  CONSTRAINT FK_PLAYER FOREIGN KEY (IDPLAYER) REFERENCES PLAYER(ID)
);
CREATE INDEX IND_ROOM_IDROOM ON ROOM_PLAYER(IDROOM);
CREATE INDEX IND_ROOM_IDPLAYER ON ROOM_PLAYER(IDPLAYER);
CREATE INDEX IND_ROOM_PLAYER_DATE_JOIN ON ROOM_PLAYER(DATE_JOIN);

CREATE TABLE GAME_BOARD(
  IDROOM NUMBER(10) NOT NULL,
  IDPLAYER NUMBER(10) NOT NULL,
  POS1 NUMBER(1) DEFAULT 0 NOT NULL,
  POS2 NUMBER(1) DEFAULT 0 NOT NULL,
  POS3 NUMBER(1) DEFAULT 0 NOT NULL,
  POS4 NUMBER(1) DEFAULT 0 NOT NULL,
  POS5 NUMBER(1) DEFAULT 0 NOT NULL,
  POS6 NUMBER(1) DEFAULT 0 NOT NULL,
  POS7 NUMBER(1) DEFAULT 0 NOT NULL,
  POS8 NUMBER(1) DEFAULT 0 NOT NULL,
  POS9 NUMBER(1) DEFAULT 0 NOT NULL,
  IN_TURN NUMBER(1) DEFAULT 0 NOT NULL,
  CONSTRAINT PK_GAME_BOARD PRIMARY KEY (IDROOM, IDPLAYER),
  CONSTRAINT FK_GAME_BOARD_ROOM FOREIGN KEY (IDROOM) REFERENCES ROOM(ID),
  CONSTRAINT FK_GAME_BOARD_PLAYER FOREIGN KEY (IDPLAYER) REFERENCES PLAYER(ID)
);
CREATE INDEX IND_GAME_BOARD_IDROOM ON GAME_BOARD(IDROOM);
CREATE INDEX IND_GAME_BOARD_IDPLAYER ON GAME_BOARD(IDPLAYER);

CREATE TABLE SCORE(
  ID NUMBER(10) NOT NULL,
  PONTUACAO_INI NUMBER(10) NOT NULL,
  PONTUACAO_FIM NUMBER(10) NOT NULL,
  DESCRICAO VARCHAR2(30) NOT NULL,
  CONSTRAINT PK_SCORE PRIMARY KEY (ID),
  CONSTRAINT UK_SCORE_PINI_PFIM UNIQUE (PONTUACAO_INI, PONTUACAO_FIM)
); --Ligação não será utilizando um ID, mas sim pelo range mín <-> máx
CREATE SEQUENCE SCORE_ID;

CREATE TABLE MATCH_HISTORY(
  IDPLAYER NUMBER(10) NOT NULL,
  IDPLAYER_OPPO NUMBER(10) NOT NULL,  
  DATE_GAME DATE NOT NULL,
  VICTORY NUMBER(1) NOT NULL,
  CONSTRAINT PK_MATCH_HISTORY PRIMARY KEY (IDPLAYER, IDPLAYER_OPPO, DATE_GAME),
  CONSTRAINT FK_MATCH_HISTORY_IDPLAYER FOREIGN KEY (IDPLAYER) REFERENCES PLAYER(ID),
  CONSTRAINT FK_MATCH_HISTORY_IDPLAYER_OP FOREIGN KEY (IDPLAYER_OPPO) REFERENCES PLAYER(ID)  
);

INSERT INTO ICON (ID, NAME, ADDRESS) VALUES(ICON_ID.NEXTVAL, 'caveira 1', 'https://i.ibb.co/Qc44psJ/caveira1.png');
INSERT INTO ICON (ID, NAME, ADDRESS) VALUES(ICON_ID.NEXTVAL, 'caveira 2', 'https://i.ibb.co/58sC8YG/caveira2.png');
INSERT INTO ICON (ID, NAME, ADDRESS) VALUES(ICON_ID.NEXTVAL, 'caveira 3', 'https://i.ibb.co/Jcx1ByH/caveira3.png');
INSERT INTO ICON (ID, NAME, ADDRESS) VALUES(ICON_ID.NEXTVAL, 'círculo', 'https://i.ibb.co/42jNJBP/circle.png');
INSERT INTO ICON (ID, NAME, ADDRESS) VALUES(ICON_ID.NEXTVAL, 'nuclear 1', 'https://i.ibb.co/894ngtN/nuclear1.png');
INSERT INTO ICON (ID, NAME, ADDRESS) VALUES(ICON_ID.NEXTVAL, 'nucelar 2', 'https://i.ibb.co/dJhwyxG/nuclear2.png');
INSERT INTO ICON (ID, NAME, ADDRESS) VALUES(ICON_ID.NEXTVAL, 'triângulo', 'https://i.ibb.co/k2v2gYF/tringule.png');
INSERT INTO ICON (ID, NAME, ADDRESS) VALUES(ICON_ID.NEXTVAL, 'x', 'https://i.ibb.co/kSXZ89L/x1.png');

INSERT INTO SCORE (ID, PONTUACAO_INI, PONTUACAO_FIM, DESCRICAO) VALUES (SCORE_ID.NEXTVAL, 0, 100, 'Iniciante IV');
INSERT INTO SCORE (ID, PONTUACAO_INI, PONTUACAO_FIM, DESCRICAO) VALUES (SCORE_ID.NEXTVAL, 101, 500, 'Iniciante III');
INSERT INTO SCORE (ID, PONTUACAO_INI, PONTUACAO_FIM, DESCRICAO) VALUES (SCORE_ID.NEXTVAL, 501, 1000, 'Iniciante II');
INSERT INTO SCORE (ID, PONTUACAO_INI, PONTUACAO_FIM, DESCRICAO) VALUES (SCORE_ID.NEXTVAL, 1001, 1500, 'Iniciante I');
COMMIT;

